# Sealed secret template — replace REPLACE_WITH_SEALED_VALUE via kubeseal
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wellnest-secrets
  namespace: {{ include "wellnest.namespace" . }}
  labels:
    {{- include "wellnest.labels" . | nindent 4 }}
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "false"
spec:
  encryptedData:
    MONGODB_ROOT_USER: REPLACE_WITH_SEALED_VALUE
    MONGODB_ROOT_PASS: REPLACE_WITH_SEALED_VALUE
    MONGODB_URI: REPLACE_WITH_SEALED_VALUE
    JWT_SECRET: REPLACE_WITH_SEALED_VALUE
  template:
    metadata:
      name: wellnest-secrets
      namespace: {{ include "wellnest.namespace" . }}
    type: Opaque
